### ISSUE TITLE
use variadic templates

### ISSUE THREAD

**Issue by laroque** [project8/midge#7]
We now make use of C++11 features and can move some templates to leverage packed arguments. In particular the `typelist_#( ... )` form could presumably become a single template, as could the _stream::call() overloads.

I haven't yet found a case where I need more arguments than provided by the existing overloads, but if someone does then this solution would be preferred to extending the overloads. Until then, this is very low priority since it works fine.

**Comment by nsoblath** [comment]
All implemented in develop now.
